**imports**

In [129]:
import pandas as pd

**This function will add a new column summarizing the measures**

In [181]:
def pm_per_month(row):
    columns = [f'D0{i+1}' if i < 9 else f'D{i+1}' for i in range(31)]
    summation = 0
    j = 0
    for i in columns:
        if row[i] != 0:
            row['total'] += row[i]
            j +=1
    row['total'] /= j
    return row['total']

In [182]:
y2010 = pd.read_csv('../data/data2010.csv', sep=';')
y2011 = pd.read_csv('../data/data2011.csv', sep=';')
y2012 = pd.read_csv('../data/data2012.csv', sep=';')
y2013 = pd.read_csv('../data/data2013.csv', sep=';')
y2014 = pd.read_csv('../data/data2014.csv', sep=';')
y2015 = pd.read_csv('../data/data2015.csv', sep=';')
y2016 = pd.read_csv('../data/data2016.csv', sep=';')
y2017 = pd.read_csv('../data/data2017.csv', sep=';')
y2018 = pd.read_csv('../data/data2018.csv', sep=';')
y2019 = pd.read_csv('../data/data2019.csv', sep=';')

In [183]:
y2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1808 entries, 0 to 1807
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1808 non-null   int64
 1   MUNICIPIO       1808 non-null   int64
 2   ESTACION        1808 non-null   int64
 3   MAGNITUD        1808 non-null   int64
 4   PUNTO_MUESTREO  1808 non-null   object
 5   ANO             1808 non-null   int64
 6   MES             1808 non-null   int64
 7   D01             1808 non-null   float64
 8   V01             1808 non-null   object
 9   D02             1808 non-null   float64
 10  V02             1808 non-null   object
 11  D03             1808 non-null   float64
 12  V03             1808 non-null   object
 13  D04             1808 non-null   float64
 14  V04             1808 non-null   object
 15  D05             1808 non-null   float64
 16  V05             1808 non-null   object
 17  D06             1808 non-null   float64
 18  V06             1808 non-null   object
 19  D07             1808 non-null   float64
 20  V07             1808 non-null   object
 21  D08             1808 non-null   float64
 22  V08             1808 non-null   object
 23  D09             1808 non-null   float64
 24  V09             1808 non-null   object
 25  D10             1808 non-null   float64
 26  V10             1808 non-null   object
 27  D11             1808 non-null   float64
 28  V11             1808 non-null   object
 29  D12             1808 non-null   float64
 30  V12             1808 non-null   object
 31  D13             1808 non-null   float64
 32  V13             1808 non-null   object
 33  D14             1808 non-null   float64
 34  V14             1808 non-null   object
 35  D15             1808 non-null   float64
 36  V15             1808 non-null   object
 37  D16             1808 non-null   float64
 38  V16             1808 non-null   object
 39  D17             1808 non-null   float64
 40  V17             1808 non-null   object
 41  D18             1808 non-null   float64
 42  V18             1808 non-null   object
 43  D19             1808 non-null   float64
 44  V19             1808 non-null   object
 45  D20             1808 non-null   float64
 46  V20             1808 non-null   object
 47  D21             1808 non-null   float64
 48  V21             1808 non-null   object
 49  D22             1808 non-null   float64
 50  V22             1808 non-null   object
 51  D23             1808 non-null   float64
 52  V23             1808 non-null   object
 53  D24             1808 non-null   float64
 54  V24             1808 non-null   object
 55  D25             1808 non-null   float64
 56  V25             1808 non-null   object
 57  D26             1808 non-null   float64
 58  V26             1808 non-null   object
 59  D27             1808 non-null   float64
 60  V27             1808 non-null   object
 61  D28             1808 non-null   float64
 62  V28             1808 non-null   object
 63  D29             1808 non-null   float64
 64  V29             1808 non-null   object
 65  D30             1808 non-null   float64
 66  V30             1808 non-null   object
 67  D31             1808 non-null   float64
 68  V31             1808 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 974.8+ KB

In [184]:
y2011.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1848 entries, 0 to 1847
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1848 non-null   int64
 1   MUNICIPIO       1848 non-null   int64
 2   ESTACION        1848 non-null   int64
 3   MAGNITUD        1848 non-null   int64
 4   PUNTO_MUESTREO  1848 non-null   object
 5   ANO             1848 non-null   int64
 6   MES             1848 non-null   int64
 7   D01             1848 non-null   float64
 8   V01             1848 non-null   object
 9   D02             1848 non-null   float64
 10  V02             1848 non-null   object
 11  D03             1848 non-null   float64
 12  V03             1848 non-null   object
 13  D04             1848 non-null   float64
 14  V04             1848 non-null   object
 15  D05             1848 non-null   float64
 16  V05             1848 non-null   object
 17  D06             1848 non-null   float64
 18  V06             1848 non-null   object
 19  D07             1848 non-null   float64
 20  V07             1848 non-null   object
 21  D08             1848 non-null   float64
 22  V08             1848 non-null   object
 23  D09             1848 non-null   float64
 24  V09             1848 non-null   object
 25  D10             1848 non-null   float64
 26  V10             1848 non-null   object
 27  D11             1848 non-null   float64
 28  V11             1848 non-null   object
 29  D12             1848 non-null   float64
 30  V12             1848 non-null   object
 31  D13             1848 non-null   float64
 32  V13             1848 non-null   object
 33  D14             1848 non-null   float64
 34  V14             1848 non-null   object
 35  D15             1848 non-null   float64
 36  V15             1848 non-null   object
 37  D16             1848 non-null   float64
 38  V16             1848 non-null   object
 39  D17             1848 non-null   float64
 40  V17             1848 non-null   object
 41  D18             1848 non-null   float64
 42  V18             1848 non-null   object
 43  D19             1848 non-null   float64
 44  V19             1848 non-null   object
 45  D20             1848 non-null   float64
 46  V20             1848 non-null   object
 47  D21             1848 non-null   float64
 48  V21             1848 non-null   object
 49  D22             1848 non-null   float64
 50  V22             1848 non-null   object
 51  D23             1848 non-null   float64
 52  V23             1848 non-null   object
 53  D24             1848 non-null   float64
 54  V24             1848 non-null   object
 55  D25             1848 non-null   float64
 56  V25             1848 non-null   object
 57  D26             1848 non-null   float64
 58  V26             1848 non-null   object
 59  D27             1848 non-null   float64
 60  V27             1848 non-null   object
 61  D28             1848 non-null   float64
 62  V28             1848 non-null   object
 63  D29             1848 non-null   float64
 64  V29             1848 non-null   object
 65  D30             1848 non-null   float64
 66  V30             1848 non-null   object
 67  D31             1848 non-null   float64
 68  V31             1848 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 996.3+ KB

In [185]:
y2012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1830 non-null   int64
 1   MUNICIPIO       1830 non-null   int64
 2   ESTACION        1830 non-null   int64
 3   MAGNITUD        1830 non-null   int64
 4   PUNTO_MUESTREO  1830 non-null   object
 5   ANO             1830 non-null   int64
 6   MES             1830 non-null   int64
 7   D01             1830 non-null   float64
 8   V01             1830 non-null   object
 9   D02             1830 non-null   float64
 10  V02             1830 non-null   object
 11  D03             1830 non-null   float64
 12  V03             1830 non-null   object
 13  D04             1830 non-null   float64
 14  V04             1830 non-null   object
 15  D05             1830 non-null   float64
 16  V05             1830 non-null   object
 17  D06             1830 non-null   float64
 18  V06             1830 non-null   object
 19  D07             1830 non-null   float64
 20  V07             1830 non-null   object
 21  D08             1830 non-null   float64
 22  V08             1830 non-null   object
 23  D09             1830 non-null   float64
 24  V09             1830 non-null   object
 25  D10             1830 non-null   float64
 26  V10             1830 non-null   object
 27  D11             1830 non-null   float64
 28  V11             1830 non-null   object
 29  D12             1830 non-null   float64
 30  V12             1830 non-null   object
 31  D13             1830 non-null   float64
 32  V13             1830 non-null   object
 33  D14             1830 non-null   float64
 34  V14             1830 non-null   object
 35  D15             1830 non-null   float64
 36  V15             1830 non-null   object
 37  D16             1830 non-null   float64
 38  V16             1830 non-null   object
 39  D17             1830 non-null   float64
 40  V17             1830 non-null   object
 41  D18             1830 non-null   float64
 42  V18             1830 non-null   object
 43  D19             1830 non-null   float64
 44  V19             1830 non-null   object
 45  D20             1830 non-null   float64
 46  V20             1830 non-null   object
 47  D21             1830 non-null   float64
 48  V21             1830 non-null   object
 49  D22             1830 non-null   float64
 50  V22             1830 non-null   object
 51  D23             1830 non-null   float64
 52  V23             1830 non-null   object
 53  D24             1830 non-null   float64
 54  V24             1830 non-null   object
 55  D25             1830 non-null   float64
 56  V25             1830 non-null   object
 57  D26             1830 non-null   float64
 58  V26             1830 non-null   object
 59  D27             1830 non-null   float64
 60  V27             1830 non-null   object
 61  D28             1830 non-null   float64
 62  V28             1830 non-null   object
 63  D29             1830 non-null   float64
 64  V29             1830 non-null   object
 65  D30             1830 non-null   float64
 66  V30             1830 non-null   object
 67  D31             1830 non-null   float64
 68  V31             1830 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 986.6+ KB

In [186]:
y2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1812 entries, 0 to 1811
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1812 non-null   int64
 1   MUNICIPIO       1812 non-null   int64
 2   ESTACION        1812 non-null   int64
 3   MAGNITUD        1812 non-null   int64
 4   PUNTO_MUESTREO  1812 non-null   object
 5   ANO             1812 non-null   int64
 6   MES             1812 non-null   int64
 7   D01             1812 non-null   float64
 8   V01             1812 non-null   object
 9   D02             1812 non-null   float64
 10  V02             1812 non-null   object
 11  D03             1812 non-null   float64
 12  V03             1812 non-null   object
 13  D04             1812 non-null   float64
 14  V04             1812 non-null   object
 15  D05             1812 non-null   float64
 16  V05             1812 non-null   object
 17  D06             1812 non-null   float64
 18  V06             1812 non-null   object
 19  D07             1812 non-null   float64
 20  V07             1812 non-null   object
 21  D08             1812 non-null   float64
 22  V08             1812 non-null   object
 23  D09             1812 non-null   float64
 24  V09             1812 non-null   object
 25  D10             1812 non-null   float64
 26  V10             1812 non-null   object
 27  D11             1812 non-null   float64
 28  V11             1812 non-null   object
 29  D12             1812 non-null   float64
 30  V12             1812 non-null   object
 31  D13             1812 non-null   float64
 32  V13             1812 non-null   object
 33  D14             1812 non-null   float64
 34  V14             1812 non-null   object
 35  D15             1812 non-null   float64
 36  V15             1812 non-null   object
 37  D16             1812 non-null   float64
 38  V16             1812 non-null   object
 39  D17             1812 non-null   float64
 40  V17             1812 non-null   object
 41  D18             1812 non-null   float64
 42  V18             1812 non-null   object
 43  D19             1812 non-null   float64
 44  V19             1812 non-null   object
 45  D20             1812 non-null   float64
 46  V20             1812 non-null   object
 47  D21             1812 non-null   float64
 48  V21             1812 non-null   object
 49  D22             1812 non-null   float64
 50  V22             1812 non-null   object
 51  D23             1812 non-null   float64
 52  V23             1812 non-null   object
 53  D24             1812 non-null   float64
 54  V24             1812 non-null   object
 55  D25             1812 non-null   float64
 56  V25             1812 non-null   object
 57  D26             1812 non-null   float64
 58  V26             1812 non-null   object
 59  D27             1812 non-null   float64
 60  V27             1812 non-null   object
 61  D28             1812 non-null   float64
 62  V28             1812 non-null   object
 63  D29             1812 non-null   float64
 64  V29             1812 non-null   object
 65  D30             1812 non-null   float64
 66  V30             1812 non-null   object
 67  D31             1812 non-null   float64
 68  V31             1812 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 976.9+ KB

In [187]:
y2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1805 entries, 0 to 1804
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1805 non-null   int64
 1   MUNICIPIO       1805 non-null   int64
 2   ESTACION        1805 non-null   int64
 3   MAGNITUD        1805 non-null   int64
 4   PUNTO_MUESTREO  1805 non-null   object
 5   ANO             1805 non-null   int64
 6   MES             1805 non-null   int64
 7   D01             1805 non-null   float64
 8   V01             1805 non-null   object
 9   D02             1805 non-null   float64
 10  V02             1805 non-null   object
 11  D03             1805 non-null   float64
 12  V03             1805 non-null   object
 13  D04             1805 non-null   float64
 14  V04             1805 non-null   object
 15  D05             1805 non-null   float64
 16  V05             1805 non-null   object
 17  D06             1805 non-null   float64
 18  V06             1805 non-null   object
 19  D07             1805 non-null   float64
 20  V07             1805 non-null   object
 21  D08             1805 non-null   float64
 22  V08             1805 non-null   object
 23  D09             1805 non-null   float64
 24  V09             1805 non-null   object
 25  D10             1805 non-null   float64
 26  V10             1805 non-null   object
 27  D11             1805 non-null   float64
 28  V11             1805 non-null   object
 29  D12             1805 non-null   float64
 30  V12             1805 non-null   object
 31  D13             1805 non-null   float64
 32  V13             1805 non-null   object
 33  D14             1805 non-null   float64
 34  V14             1805 non-null   object
 35  D15             1805 non-null   float64
 36  V15             1805 non-null   object
 37  D16             1805 non-null   float64
 38  V16             1805 non-null   object
 39  D17             1805 non-null   float64
 40  V17             1805 non-null   object
 41  D18             1805 non-null   float64
 42  V18             1805 non-null   object
 43  D19             1805 non-null   float64
 44  V19             1805 non-null   object
 45  D20             1805 non-null   float64
 46  V20             1805 non-null   object
 47  D21             1805 non-null   float64
 48  V21             1805 non-null   object
 49  D22             1805 non-null   float64
 50  V22             1805 non-null   object
 51  D23             1805 non-null   float64
 52  V23             1805 non-null   object
 53  D24             1805 non-null   float64
 54  V24             1805 non-null   object
 55  D25             1805 non-null   float64
 56  V25             1805 non-null   object
 57  D26             1805 non-null   float64
 58  V26             1805 non-null   object
 59  D27             1805 non-null   float64
 60  V27             1805 non-null   object
 61  D28             1805 non-null   float64
 62  V28             1805 non-null   object
 63  D29             1805 non-null   float64
 64  V29             1805 non-null   object
 65  D30             1805 non-null   float64
 66  V30             1805 non-null   object
 67  D31             1805 non-null   float64
 68  V31             1805 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 973.1+ KB

In [188]:
y2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1812 entries, 0 to 1811
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1812 non-null   int64
 1   MUNICIPIO       1812 non-null   int64
 2   ESTACION        1812 non-null   int64
 3   MAGNITUD        1812 non-null   int64
 4   PUNTO_MUESTREO  1812 non-null   object
 5   ANO             1812 non-null   int64
 6   MES             1812 non-null   int64
 7   D01             1812 non-null   float64
 8   V01             1812 non-null   object
 9   D02             1812 non-null   float64
 10  V02             1812 non-null   object
 11  D03             1812 non-null   float64
 12  V03             1812 non-null   object
 13  D04             1812 non-null   float64
 14  V04             1812 non-null   object
 15  D05             1812 non-null   float64
 16  V05             1812 non-null   object
 17  D06             1812 non-null   float64
 18  V06             1812 non-null   object
 19  D07             1812 non-null   float64
 20  V07             1812 non-null   object
 21  D08             1812 non-null   float64
 22  V08             1812 non-null   object
 23  D09             1812 non-null   float64
 24  V09             1812 non-null   object
 25  D10             1812 non-null   float64
 26  V10             1812 non-null   object
 27  D11             1812 non-null   float64
 28  V11             1812 non-null   object
 29  D12             1812 non-null   float64
 30  V12             1812 non-null   object
 31  D13             1812 non-null   float64
 32  V13             1812 non-null   object
 33  D14             1812 non-null   float64
 34  V14             1812 non-null   object
 35  D15             1812 non-null   float64
 36  V15             1812 non-null   object
 37  D16             1812 non-null   float64
 38  V16             1812 non-null   object
 39  D17             1812 non-null   float64
 40  V17             1812 non-null   object
 41  D18             1812 non-null   float64
 42  V18             1812 non-null   object
 43  D19             1812 non-null   float64
 44  V19             1812 non-null   object
 45  D20             1812 non-null   float64
 46  V20             1812 non-null   object
 47  D21             1812 non-null   float64
 48  V21             1812 non-null   object
 49  D22             1812 non-null   float64
 50  V22             1812 non-null   object
 51  D23             1812 non-null   float64
 52  V23             1812 non-null   object
 53  D24             1812 non-null   float64
 54  V24             1812 non-null   object
 55  D25             1812 non-null   float64
 56  V25             1812 non-null   object
 57  D26             1812 non-null   float64
 58  V26             1812 non-null   object
 59  D27             1812 non-null   float64
 60  V27             1812 non-null   object
 61  D28             1812 non-null   float64
 62  V28             1812 non-null   object
 63  D29             1812 non-null   float64
 64  V29             1812 non-null   object
 65  D30             1812 non-null   float64
 66  V30             1812 non-null   object
 67  D31             1812 non-null   float64
 68  V31             1812 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 976.9+ KB

In [189]:
y2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1812 entries, 0 to 1811
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1812 non-null   int64
 1   MUNICIPIO       1812 non-null   int64
 2   ESTACION        1812 non-null   int64
 3   MAGNITUD        1812 non-null   int64
 4   PUNTO_MUESTREO  1812 non-null   object
 5   ANO             1812 non-null   int64
 6   MES             1812 non-null   int64
 7   D01             1812 non-null   float64
 8   V01             1812 non-null   object
 9   D02             1812 non-null   float64
 10  V02             1812 non-null   object
 11  D03             1812 non-null   float64
 12  V03             1812 non-null   object
 13  D04             1812 non-null   float64
 14  V04             1812 non-null   object
 15  D05             1812 non-null   float64
 16  V05             1812 non-null   object
 17  D06             1812 non-null   float64
 18  V06             1812 non-null   object
 19  D07             1812 non-null   float64
 20  V07             1812 non-null   object
 21  D08             1812 non-null   float64
 22  V08             1812 non-null   object
 23  D09             1812 non-null   float64
 24  V09             1812 non-null   object
 25  D10             1812 non-null   float64
 26  V10             1812 non-null   object
 27  D11             1812 non-null   float64
 28  V11             1812 non-null   object
 29  D12             1812 non-null   float64
 30  V12             1812 non-null   object
 31  D13             1812 non-null   float64
 32  V13             1812 non-null   object
 33  D14             1812 non-null   float64
 34  V14             1812 non-null   object
 35  D15             1812 non-null   float64
 36  V15             1812 non-null   object
 37  D16             1812 non-null   float64
 38  V16             1812 non-null   object
 39  D17             1812 non-null   float64
 40  V17             1812 non-null   object
 41  D18             1812 non-null   float64
 42  V18             1812 non-null   object
 43  D19             1812 non-null   float64
 44  V19             1812 non-null   object
 45  D20             1812 non-null   float64
 46  V20             1812 non-null   object
 47  D21             1812 non-null   float64
 48  V21             1812 non-null   object
 49  D22             1812 non-null   float64
 50  V22             1812 non-null   object
 51  D23             1812 non-null   float64
 52  V23             1812 non-null   object
 53  D24             1812 non-null   float64
 54  V24             1812 non-null   object
 55  D25             1812 non-null   float64
 56  V25             1812 non-null   object
 57  D26             1812 non-null   float64
 58  V26             1812 non-null   object
 59  D27             1812 non-null   float64
 60  V27             1812 non-null   object
 61  D28             1812 non-null   float64
 62  V28             1812 non-null   object
 63  D29             1812 non-null   float64
 64  V29             1812 non-null   object
 65  D30             1812 non-null   float64
 66  V30             1812 non-null   object
 67  D31             1812 non-null   float64
 68  V31             1812 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 976.9+ KB

In [190]:
y2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1812 entries, 0 to 1811
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1812 non-null   int64
 1   MUNICIPIO       1812 non-null   int64
 2   ESTACION        1812 non-null   int64
 3   MAGNITUD        1812 non-null   int64
 4   PUNTO_MUESTREO  1812 non-null   object
 5   ANO             1812 non-null   int64
 6   MES             1812 non-null   int64
 7   D01             1812 non-null   float64
 8   V01             1812 non-null   object
 9   D02             1812 non-null   float64
 10  V02             1812 non-null   object
 11  D03             1812 non-null   float64
 12  V03             1812 non-null   object
 13  D04             1812 non-null   float64
 14  V04             1812 non-null   object
 15  D05             1812 non-null   float64
 16  V05             1812 non-null   object
 17  D06             1812 non-null   float64
 18  V06             1812 non-null   object
 19  D07             1812 non-null   float64
 20  V07             1812 non-null   object
 21  D08             1812 non-null   float64
 22  V08             1812 non-null   object
 23  D09             1812 non-null   float64
 24  V09             1812 non-null   object
 25  D10             1812 non-null   float64
 26  V10             1812 non-null   object
 27  D11             1812 non-null   float64
 28  V11             1812 non-null   object
 29  D12             1812 non-null   float64
 30  V12             1812 non-null   object
 31  D13             1812 non-null   float64
 32  V13             1812 non-null   object
 33  D14             1812 non-null   float64
 34  V14             1812 non-null   object
 35  D15             1812 non-null   float64
 36  V15             1812 non-null   object
 37  D16             1812 non-null   float64
 38  V16             1812 non-null   object
 39  D17             1812 non-null   float64
 40  V17             1812 non-null   object
 41  D18             1812 non-null   float64
 42  V18             1812 non-null   object
 43  D19             1812 non-null   float64
 44  V19             1812 non-null   object
 45  D20             1812 non-null   float64
 46  V20             1812 non-null   object
 47  D21             1812 non-null   float64
 48  V21             1812 non-null   object
 49  D22             1812 non-null   float64
 50  V22             1812 non-null   object
 51  D23             1812 non-null   float64
 52  V23             1812 non-null   object
 53  D24             1812 non-null   float64
 54  V24             1812 non-null   object
 55  D25             1812 non-null   float64
 56  V25             1812 non-null   object
 57  D26             1812 non-null   float64
 58  V26             1812 non-null   object
 59  D27             1812 non-null   float64
 60  V27             1812 non-null   object
 61  D28             1812 non-null   float64
 62  V28             1812 non-null   object
 63  D29             1812 non-null   float64
 64  V29             1812 non-null   object
 65  D30             1812 non-null   float64
 66  V30             1812 non-null   object
 67  D31             1812 non-null   float64
 68  V31             1812 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 976.9+ KB

In [191]:
y2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1806 entries, 0 to 1805
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1806 non-null   int64
 1   MUNICIPIO       1806 non-null   int64
 2   ESTACION        1806 non-null   int64
 3   MAGNITUD        1806 non-null   int64
 4   PUNTO_MUESTREO  1806 non-null   object
 5   ANO             1806 non-null   int64
 6   MES             1806 non-null   int64
 7   D01             1806 non-null   float64
 8   V01             1806 non-null   object
 9   D02             1806 non-null   float64
 10  V02             1806 non-null   object
 11  D03             1806 non-null   float64
 12  V03             1806 non-null   object
 13  D04             1806 non-null   float64
 14  V04             1806 non-null   object
 15  D05             1806 non-null   float64
 16  V05             1806 non-null   object
 17  D06             1806 non-null   float64
 18  V06             1806 non-null   object
 19  D07             1806 non-null   float64
 20  V07             1806 non-null   object
 21  D08             1806 non-null   float64
 22  V08             1806 non-null   object
 23  D09             1806 non-null   float64
 24  V09             1806 non-null   object
 25  D10             1806 non-null   float64
 26  V10             1806 non-null   object
 27  D11             1806 non-null   float64
 28  V11             1806 non-null   object
 29  D12             1806 non-null   float64
 30  V12             1806 non-null   object
 31  D13             1806 non-null   float64
 32  V13             1806 non-null   object
 33  D14             1806 non-null   float64
 34  V14             1806 non-null   object
 35  D15             1806 non-null   float64
 36  V15             1806 non-null   object
 37  D16             1806 non-null   float64
 38  V16             1806 non-null   object
 39  D17             1806 non-null   float64
 40  V17             1806 non-null   object
 41  D18             1806 non-null   float64
 42  V18             1806 non-null   object
 43  D19             1806 non-null   float64
 44  V19             1806 non-null   object
 45  D20             1806 non-null   float64
 46  V20             1806 non-null   object
 47  D21             1806 non-null   float64
 48  V21             1806 non-null   object
 49  D22             1806 non-null   float64
 50  V22             1806 non-null   object
 51  D23             1806 non-null   float64
 52  V23             1806 non-null   object
 53  D24             1806 non-null   float64
 54  V24             1806 non-null   object
 55  D25             1806 non-null   float64
 56  V25             1806 non-null   object
 57  D26             1806 non-null   float64
 58  V26             1806 non-null   object
 59  D27             1806 non-null   float64
 60  V27             1806 non-null   object
 61  D28             1806 non-null   float64
 62  V28             1806 non-null   object
 63  D29             1806 non-null   float64
 64  V29             1806 non-null   object
 65  D30             1806 non-null   float64
 66  V30             1806 non-null   object
 67  D31             1806 non-null   float64
 68  V31             1806 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 973.7+ KB

In [192]:
y2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1836 entries, 0 to 1835
Data columns (total 69 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PROVINCIA       1836 non-null   int64
 1   MUNICIPIO       1836 non-null   int64
 2   ESTACION        1836 non-null   int64
 3   MAGNITUD        1836 non-null   int64
 4   PUNTO_MUESTREO  1836 non-null   object
 5   ANO             1836 non-null   int64
 6   MES             1836 non-null   int64
 7   D01             1836 non-null   float64
 8   V01             1836 non-null   object
 9   D02             1836 non-null   float64
 10  V02             1836 non-null   object
 11  D03             1836 non-null   float64
 12  V03             1836 non-null   object
 13  D04             1836 non-null   float64
 14  V04             1836 non-null   object
 15  D05             1836 non-null   float64
 16  V05             1836 non-null   object
 17  D06             1836 non-null   float64
 18  V06             1836 non-null   object
 19  D07             1836 non-null   float64
 20  V07             1836 non-null   object
 21  D08             1836 non-null   float64
 22  V08             1836 non-null   object
 23  D09             1836 non-null   float64
 24  V09             1836 non-null   object
 25  D10             1836 non-null   float64
 26  V10             1836 non-null   object
 27  D11             1836 non-null   float64
 28  V11             1836 non-null   object
 29  D12             1836 non-null   float64
 30  V12             1836 non-null   object
 31  D13             1836 non-null   float64
 32  V13             1836 non-null   object
 33  D14             1836 non-null   float64
 34  V14             1836 non-null   object
 35  D15             1836 non-null   float64
 36  V15             1836 non-null   object
 37  D16             1836 non-null   float64
 38  V16             1836 non-null   object
 39  D17             1836 non-null   float64
 40  V17             1836 non-null   object
 41  D18             1836 non-null   float64
 42  V18             1836 non-null   object
 43  D19             1836 non-null   float64
 44  V19             1836 non-null   object
 45  D20             1836 non-null   float64
 46  V20             1836 non-null   object
 47  D21             1836 non-null   float64
 48  V21             1836 non-null   object
 49  D22             1836 non-null   float64
 50  V22             1836 non-null   object
 51  D23             1836 non-null   float64
 52  V23             1836 non-null   object
 53  D24             1836 non-null   float64
 54  V24             1836 non-null   object
 55  D25             1836 non-null   float64
 56  V25             1836 non-null   object
 57  D26             1836 non-null   float64
 58  V26             1836 non-null   object
 59  D27             1836 non-null   float64
 60  V27             1836 non-null   object
 61  D28             1836 non-null   float64
 62  V28             1836 non-null   object
 63  D29             1836 non-null   float64
 64  V29             1836 non-null   object
 65  D30             1836 non-null   float64
 66  V30             1836 non-null   object
 67  D31             1836 non-null   float64
 68  V31             1836 non-null   object
dtypes: float64(31), int64(6), object(32)
memory usage: 989.8+ KB

Exploring particles <2.5 micrograms
==

In [193]:
pm2019 = y2019[y2019['MAGNITUD'] == 9]
pm2019

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
108,28,79,8,9,28079008_9_47,2019,1,19.0,V,21.0,...,7.0,V,5.0,V,7.0,V,6.0,V,5.0,V
109,28,79,8,9,28079008_9_47,2019,2,4.0,V,4.0,...,12.0,V,16.0,V,0.0,N,0.0,N,0.0,N
110,28,79,8,9,28079008_9_47,2019,3,12.0,V,12.0,...,14.0,V,13.0,V,10.0,V,10.0,V,11.0,V
111,28,79,8,9,28079008_9_47,2019,4,8.0,V,10.0,...,9.0,V,7.0,V,8.0,V,7.0,V,0.0,N
112,28,79,8,9,28079008_9_47,2019,5,6.0,V,6.0,...,6.0,V,4.0,V,5.0,V,6.0,V,7.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1567,28,79,56,9,28079056_9_47,2019,8,12.0,V,17.0,...,13.0,V,24.0,N,19.0,V,19.0,V,19.0,V
1568,28,79,56,9,28079056_9_47,2019,9,17.0,V,14.0,...,12.0,V,13.0,V,12.0,V,15.0,V,0.0,N
1569,28,79,56,9,28079056_9_47,2019,10,11.0,V,6.0,...,15.0,V,20.0,V,35.0,V,23.0,V,9.0,V
1570,28,79,56,9,28079056_9_47,2019,11,7.0,V,6.0,...,8.0,V,10.0,V,13.0,V,12.0,V,0.0,N
1571,28,79,56,9,28079056_9_47,2019,12,9.0,V,4.0,...,16.0,V,24.0,V,19.0,V,21.0,V,31.0,V

In [194]:
pm2018 = y2018[y2018['MAGNITUD'] == 9]
pm2018

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
108,28,79,8,9,28079008_9_47,2018,1,5.0,V,6.0,...,3.0,V,4.0,V,9.0,V,11.0,V,12.0,V
109,28,79,8,9,28079008_9_47,2018,2,14.0,V,4.0,...,13.0,V,8.0,V,0.0,N,0.0,N,0.0,N
110,28,79,8,9,28079008_9_47,2018,3,3.0,V,10.0,...,5.0,V,7.0,V,5.0,V,3.0,V,4.0,V
111,28,79,8,9,28079008_9_47,2018,4,5.0,V,7.0,...,7.0,V,8.0,V,4.0,V,3.0,V,0.0,N
112,28,79,8,9,28079008_9_47,2018,5,3.0,V,6.0,...,8.0,V,7.0,V,9.0,V,8.0,V,9.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,28,79,50,9,28079050_9_47,2018,8,13.0,V,14.0,...,14.0,V,14.0,V,15.0,V,12.0,V,15.0,V
1322,28,79,50,9,28079050_9_47,2018,9,12.0,V,13.0,...,12.0,V,12.0,V,11.0,V,12.0,V,0.0,N
1323,28,79,50,9,28079050_9_47,2018,10,5.0,V,4.0,...,13.0,V,11.0,V,13.0,V,21.0,V,13.0,V
1324,28,79,50,9,28079050_9_47,2018,11,12.0,V,6.0,...,11.0,V,25.0,V,23.0,V,14.0,V,0.0,N
1325,28,79,50,9,28079050_9_47,2018,12,15.0,V,22.0,...,25.0,V,13.0,V,6.0,V,8.0,V,15.0,V

In [195]:
pm2018['total'] = pm2018.apply(lambda x : pm_per_month(x), axis=1)

KeyError: 'total'

In [196]:
pm2018

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
108,28,79,8,9,28079008_9_47,2018,1,5.0,V,6.0,...,3.0,V,4.0,V,9.0,V,11.0,V,12.0,V
109,28,79,8,9,28079008_9_47,2018,2,14.0,V,4.0,...,13.0,V,8.0,V,0.0,N,0.0,N,0.0,N
110,28,79,8,9,28079008_9_47,2018,3,3.0,V,10.0,...,5.0,V,7.0,V,5.0,V,3.0,V,4.0,V
111,28,79,8,9,28079008_9_47,2018,4,5.0,V,7.0,...,7.0,V,8.0,V,4.0,V,3.0,V,0.0,N
112,28,79,8,9,28079008_9_47,2018,5,3.0,V,6.0,...,8.0,V,7.0,V,9.0,V,8.0,V,9.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,28,79,50,9,28079050_9_47,2018,8,13.0,V,14.0,...,14.0,V,14.0,V,15.0,V,12.0,V,15.0,V
1322,28,79,50,9,28079050_9_47,2018,9,12.0,V,13.0,...,12.0,V,12.0,V,11.0,V,12.0,V,0.0,N
1323,28,79,50,9,28079050_9_47,2018,10,5.0,V,4.0,...,13.0,V,11.0,V,13.0,V,21.0,V,13.0,V
1324,28,79,50,9,28079050_9_47,2018,11,12.0,V,6.0,...,11.0,V,25.0,V,23.0,V,14.0,V,0.0,N
1325,28,79,50,9,28079050_9_47,2018,12,15.0,V,22.0,...,25.0,V,13.0,V,6.0,V,8.0,V,15.0,V

In [197]:
pm2019 = y2019[y2019['MAGNITUD'] == 9]
pm2019['total'] = [i for i in range(len(pm2019))]
pm2019['total'] = pm2019.apply(lambda x : pm_per_month(x), axis=1)
pm2019

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/893672357.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2019['total'] = [i for i in range(len(pm2019))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/893672357.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2019['total'] = pm2019.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2019,1,19.0,V,21.0,...,V,5.0,V,7.0,V,6.0,V,5.0,V,13.806452
109,28,79,8,9,28079008_9_47,2019,2,4.0,V,4.0,...,V,16.0,V,0.0,N,0.0,N,0.0,N,13.250000
110,28,79,8,9,28079008_9_47,2019,3,12.0,V,12.0,...,V,13.0,V,10.0,V,10.0,V,11.0,V,15.258065
111,28,79,8,9,28079008_9_47,2019,4,8.0,V,10.0,...,V,7.0,V,8.0,V,7.0,V,0.0,N,7.666667
112,28,79,8,9,28079008_9_47,2019,5,6.0,V,6.0,...,V,4.0,V,5.0,V,6.0,V,7.0,V,6.677419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1567,28,79,56,9,28079056_9_47,2019,8,12.0,V,17.0,...,V,24.0,N,19.0,V,19.0,V,19.0,V,15.709677
1568,28,79,56,9,28079056_9_47,2019,9,17.0,V,14.0,...,V,13.0,V,12.0,V,15.0,V,0.0,N,15.400000
1569,28,79,56,9,28079056_9_47,2019,10,11.0,V,6.0,...,V,20.0,V,35.0,V,23.0,V,9.0,V,15.129032
1570,28,79,56,9,28079056_9_47,2019,11,7.0,V,6.0,...,V,10.0,V,13.0,V,12.0,V,0.0,N,11.100000
1571,28,79,56,9,28079056_9_47,2019,12,9.0,V,4.0,...,V,24.0,V,19.0,V,21.0,V,31.0,V,15.387097

In [198]:
pm2017 = y2017[y2017['MAGNITUD'] == 9]
pm2017['total'] = [i for i in range(len(pm2017))]
pm2017['total'] = pm2017.apply(lambda x : pm_per_month(x), axis=1)
pm2017

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2875457820.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2017['total'] = [i for i in range(len(pm2017))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2875457820.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2017['total'] = pm2017.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2017,1,20.0,V,21.0,...,V,6.0,V,9.0,V,8.0,V,13.0,V,13.838710
109,28,79,8,9,28079008_9_47,2017,2,19.0,V,6.0,...,V,6.0,V,0.0,N,0.0,N,0.0,N,11.892857
110,28,79,8,9,28079008_9_47,2017,3,8.0,V,14.0,...,V,10.0,V,12.0,V,14.0,V,12.0,V,9.967742
111,28,79,8,9,28079008_9_47,2017,4,4.0,V,4.0,...,V,7.0,V,7.0,V,7.0,V,0.0,N,8.566667
112,28,79,8,9,28079008_9_47,2017,5,5.0,V,7.0,...,V,10.0,V,10.0,V,9.0,V,9.0,V,8.870968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,28,79,50,9,28079050_9_47,2017,8,8.0,V,7.0,...,V,6.0,V,7.0,V,8.0,V,5.0,V,9.741935
1328,28,79,50,9,28079050_9_47,2017,9,5.0,V,6.0,...,V,11.0,V,12.0,V,11.0,V,0.0,N,9.933333
1329,28,79,50,9,28079050_9_47,2017,10,7.0,V,5.0,...,V,6.0,V,5.0,V,4.0,V,8.0,V,10.451613
1330,28,79,50,9,28079050_9_47,2017,11,11.0,V,11.0,...,V,19.0,V,8.0,V,4.0,V,0.0,N,12.333333
1331,28,79,50,9,28079050_9_47,2017,12,4.0,V,3.0,...,V,4.0,V,6.0,V,8.0,V,6.0,V,11.806452

In [199]:
pm2016 = y2016[y2016['MAGNITUD'] == 9]
pm2016['total'] = [i for i in range(len(pm2016))]
pm2016['total'] = pm2016.apply(lambda x : pm_per_month(x), axis=1)
pm2016

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/1396590018.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2016['total'] = [i for i in range(len(pm2016))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/1396590018.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2016['total'] = pm2016.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2016,1,15.0,V,7.0,...,V,22.0,V,11.0,V,12.0,V,12.0,V,13.483871
109,28,79,8,9,28079008_9_47,2016,2,23.0,V,30.0,...,V,4.0,V,8.0,V,0.0,N,0.0,N,12.517241
110,28,79,8,9,28079008_9_47,2016,3,13.0,V,12.0,...,V,6.0,V,8.0,V,13.0,V,5.0,V,10.225806
111,28,79,8,9,28079008_9_47,2016,4,6.0,V,8.0,...,V,6.0,V,8.0,V,7.0,V,0.0,N,7.600000
112,28,79,8,9,28079008_9_47,2016,5,4.0,V,4.0,...,V,6.0,V,6.0,V,6.0,V,6.0,V,7.935484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,28,79,50,9,28079050_9_47,2016,8,8.0,V,10.0,...,V,18.0,V,12.0,V,8.0,V,10.0,V,10.967742
1328,28,79,50,9,28079050_9_47,2016,9,9.0,V,11.0,...,V,4.0,V,10.0,V,11.0,V,0.0,N,12.300000
1329,28,79,50,9,28079050_9_47,2016,10,11.0,V,9.0,...,V,15.0,V,14.0,V,10.0,V,13.0,V,13.258065
1330,28,79,50,9,28079050_9_47,2016,11,17.0,V,18.0,...,V,6.0,V,6.0,V,5.0,V,0.0,N,13.066667
1331,28,79,50,9,28079050_9_47,2016,12,5.0,V,13.0,...,V,12.0,V,18.0,V,19.0,V,17.0,V,15.838710

In [200]:
pm2015 = y2015[y2015['MAGNITUD'] == 9]
pm2015['total'] = [i for i in range(len(pm2015))]
pm2015['total'] = pm2015.apply(lambda x : pm_per_month(x), axis=1)
pm2015

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/725913540.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2015['total'] = [i for i in range(len(pm2015))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/725913540.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2015['total'] = pm2015.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2015,1,33.0,V,22.0,...,N,1.0,N,1.0,N,1.0,N,1.0,N,10.774194
109,28,79,8,9,28079008_9_47,2015,2,1.0,N,1.0,...,V,11.0,V,0.0,N,0.0,N,0.0,N,7.750000
110,28,79,8,9,28079008_9_47,2015,3,7.0,V,14.0,...,V,15.0,V,8.0,V,10.0,V,13.0,V,12.451613
111,28,79,8,9,28079008_9_47,2015,4,8.0,V,7.0,...,V,7.0,V,10.0,V,12.0,V,0.0,N,10.000000
112,28,79,8,9,28079008_9_47,2015,5,9.0,V,9.0,...,V,14.0,V,13.0,V,13.0,V,12.0,V,10.806452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,28,79,50,9,28079050_9_47,2015,8,5.0,V,9.0,...,V,10.0,V,9.0,V,10.0,V,13.0,V,11.677419
1328,28,79,50,9,28079050_9_47,2015,9,11.0,V,10.0,...,V,7.0,V,9.0,V,9.0,V,0.0,N,10.533333
1329,28,79,50,9,28079050_9_47,2015,10,12.0,V,11.0,...,V,6.0,V,9.0,V,14.0,V,10.0,V,13.322581
1330,28,79,50,9,28079050_9_47,2015,11,7.0,V,5.0,...,V,9.0,V,13.0,V,14.0,V,0.0,N,15.966667
1331,28,79,50,9,28079050_9_47,2015,12,17.0,V,30.0,...,V,15.0,V,15.0,V,12.0,V,14.0,V,23.354839

In [201]:
pm2014 = y2014[y2014['MAGNITUD'] == 9]
pm2014['total'] = [i for i in range(len(pm2014))]
pm2014['total'] = pm2014.apply(lambda x : pm_per_month(x), axis=1)
pm2014

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/1642419583.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2014['total'] = [i for i in range(len(pm2014))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/1642419583.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2014['total'] = pm2014.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2014,1,7.0,V,7.0,...,V,7.0,V,9.0,V,8.0,V,10.0,V,10.225806
109,28,79,8,9,28079008_9_47,2014,2,6.0,V,7.0,...,V,8.0,V,0.0,N,0.0,N,0.0,N,9.035714
110,28,79,8,9,28079008_9_47,2014,3,8.0,V,6.0,...,V,11.0,V,14.0,V,8.0,V,10.0,V,12.096774
111,28,79,8,9,28079008_9_47,2014,4,9.0,V,10.0,...,V,8.0,V,10.0,V,8.0,V,0.0,N,10.566667
112,28,79,8,9,28079008_9_47,2014,5,8.0,V,7.0,...,V,9.0,V,9.0,V,7.0,V,6.0,V,10.419355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1332,28,79,50,9,28079050_9_47,2014,8,18.0,V,11.0,...,V,12.0,V,10.0,V,12.0,V,12.0,V,12.451613
1333,28,79,50,9,28079050_9_47,2014,9,11.0,V,13.0,...,V,16.0,V,18.0,V,11.0,V,0.0,N,13.266667
1334,28,79,50,9,28079050_9_47,2014,10,12.0,V,12.0,...,V,20.0,V,22.0,V,20.0,V,14.0,V,15.354839
1335,28,79,50,9,28079050_9_47,2014,11,16.0,V,14.0,...,V,8.0,V,8.0,V,9.0,V,0.0,N,14.200000
1336,28,79,50,9,28079050_9_47,2014,12,11.0,V,8.0,...,V,5.0,V,4.0,V,8.0,N,0.0,N,13.800000

In [202]:
pm2013 = y2013[y2013['MAGNITUD'] == 9]
pm2013['total'] = [i for i in range(len(pm2013))]
pm2013['total'] = pm2013.apply(lambda x : pm_per_month(x), axis=1)
pm2013

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2492119050.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2013['total'] = [i for i in range(len(pm2013))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2492119050.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2013['total'] = pm2013.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2013,1,10.0,V,14.0,...,N,0.0,N,0.0,N,0.0,N,0.0,N,11.857143
109,28,79,8,9,28079008_9_47,2013,2,6.0,N,4.0,...,V,10.0,V,0.0,N,0.0,N,0.0,N,10.214286
110,28,79,8,9,28079008_9_47,2013,3,12.0,V,12.0,...,V,7.0,V,6.0,V,8.0,V,8.0,V,9.193548
111,28,79,8,9,28079008_9_47,2013,4,8.0,V,9.0,...,V,5.0,V,7.0,V,8.0,V,0.0,N,10.233333
112,28,79,8,9,28079008_9_47,2013,5,8.0,V,6.0,...,V,9.0,V,8.0,V,8.0,V,10.0,V,9.322581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,28,79,50,9,28079050_9_47,2013,8,18.0,V,15.0,...,V,8.0,V,10.0,V,11.0,V,7.0,V,13.548387
1328,28,79,50,9,28079050_9_47,2013,9,10.0,V,12.0,...,V,8.0,V,6.0,V,8.0,V,0.0,N,12.800000
1329,28,79,50,9,28079050_9_47,2013,10,7.0,V,10.0,...,V,15.0,V,7.0,V,8.0,V,15.0,V,21.290323
1330,28,79,50,9,28079050_9_47,2013,11,11.0,V,13.0,...,V,9.0,V,15.0,V,12.0,V,0.0,N,11.366667
1331,28,79,50,9,28079050_9_47,2013,12,5.0,V,12.0,...,V,6.0,V,9.0,V,13.0,V,10.0,V,14.000000

In [203]:
pm2012 = y2012[y2012['MAGNITUD'] == 9]
pm2012['total'] = [i for i in range(len(pm2012))]
pm2012['total'] = pm2012.apply(lambda x : pm_per_month(x), axis=1)
pm2012

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2089494871.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2012['total'] = [i for i in range(len(pm2012))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2089494871.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2012['total'] = pm2012.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2012,1,27.0,V,8.0,...,V,6.0,V,6.0,V,14.0,V,18.0,V,17.419355
109,28,79,8,9,28079008_9_47,2012,2,20.0,V,11.0,...,V,17.0,V,20.0,V,0.0,N,0.0,N,12.448276
110,28,79,8,9,28079008_9_47,2012,3,18.0,V,19.0,...,V,21.0,V,16.0,V,14.0,V,16.0,V,13.225806
111,28,79,8,9,28079008_9_47,2012,4,15.0,V,11.0,...,V,7.0,V,6.0,V,7.0,V,0.0,N,9.366667
112,28,79,8,9,28079008_9_47,2012,5,8.0,V,11.0,...,V,11.0,V,13.0,V,20.0,V,19.0,V,13.580645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,28,79,50,9,28079050_9_47,2012,8,8.0,V,8.0,...,V,8.0,V,7.0,V,7.0,V,4.0,V,13.096774
1346,28,79,50,9,28079050_9_47,2012,9,5.0,V,5.0,...,V,8.0,V,5.0,V,8.0,V,0.0,N,13.666667
1347,28,79,50,9,28079050_9_47,2012,10,14.0,V,15.0,...,V,4.0,V,11.0,V,9.0,V,11.0,V,14.387097
1348,28,79,50,9,28079050_9_47,2012,11,9.0,V,9.0,...,V,8.0,V,9.0,V,8.0,V,0.0,N,13.066667
1349,28,79,50,9,28079050_9_47,2012,12,7.0,V,13.0,...,V,18.0,V,19.0,V,18.0,V,14.0,V,16.290323

In [204]:
pm2011 = y2011[y2011['MAGNITUD'] == 9]
pm2011['total'] = [i for i in range(len(pm2011))]
pm2011['total'] = pm2011.apply(lambda x : pm_per_month(x), axis=1)
pm2011

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/1017190952.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2011['total'] = [i for i in range(len(pm2011))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/1017190952.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2011['total'] = pm2011.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2011,1,11.0,V,11.0,...,V,10.0,V,11.0,V,13.0,V,11.0,V,14.774194
109,28,79,8,9,28079008_9_47,2011,2,14.0,V,17.0,...,V,6.0,V,0.0,N,0.0,N,0.0,N,15.142857
110,28,79,8,9,28079008_9_47,2011,3,8.0,V,12.0,...,V,0.0,N,0.0,N,11.0,V,17.0,V,13.241379
111,28,79,8,9,28079008_9_47,2011,4,19.0,V,19.0,...,V,19.0,V,17.0,V,9.0,V,0.0,N,15.433333
112,28,79,8,9,28079008_9_47,2011,5,9.0,V,10.0,...,V,12.0,V,14.0,V,16.0,V,9.0,V,13.241379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1363,28,79,50,9,28079050_9_47,2011,8,16.0,V,14.0,...,V,10.0,V,12.0,V,11.0,V,11.0,V,14.387097
1364,28,79,50,9,28079050_9_47,2011,9,8.0,V,8.0,...,V,13.0,V,10.0,V,9.0,V,0.0,N,13.633333
1365,28,79,50,9,28079050_9_47,2011,10,12.0,V,11.0,...,V,5.0,V,5.0,V,6.0,V,8.0,V,10.064516
1366,28,79,50,9,28079050_9_47,2011,11,9.0,V,8.0,...,V,11.0,V,13.0,V,12.0,V,0.0,N,10.133333
1367,28,79,50,9,28079050_9_47,2011,12,12.0,V,7.0,...,V,9.0,V,5.0,V,10.0,V,13.0,V,11.354839

In [205]:
pm2010 = y2010[y2010['MAGNITUD'] == 9]
pm2010['total'] = [i for i in range(len(pm2010))]
pm2010['total'] = pm2010.apply(lambda x : pm_per_month(x), axis=1)
pm2010

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2113356566.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2010['total'] = [i for i in range(len(pm2010))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2113356566.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm2010['total'] = pm2010.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
108,28,79,8,9,28079008_9_47,2010,1,7.0,V,9.0,...,V,12.0,V,11.0,V,5.0,V,6.0,V,9.580645
109,28,79,8,9,28079008_9_47,2010,2,7.0,V,9.0,...,V,3.0,V,0.0,N,0.0,N,0.0,N,8.321429
110,28,79,8,9,28079008_9_47,2010,3,7.0,V,5.0,...,V,12.0,V,14.0,V,10.0,V,9.0,V,14.096774
111,28,79,8,9,28079008_9_47,2010,4,6.0,V,9.0,...,V,14.0,V,16.0,V,14.0,V,0.0,N,11.700000
112,28,79,8,9,28079008_9_47,2010,5,10.0,V,6.0,...,V,11.0,V,10.0,V,13.0,V,11.0,V,11.483871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,28,79,50,9,28079050_9_47,2010,8,0.0,N,0.0,...,V,21.0,V,12.0,V,11.0,V,17.0,V,20.785714
1326,28,79,50,9,28079050_9_47,2010,9,17.0,V,16.0,...,V,12.0,V,11.0,V,16.0,V,0.0,N,15.600000
1327,28,79,50,9,28079050_9_47,2010,10,16.0,V,15.0,...,V,22.0,V,19.0,V,6.0,V,7.0,V,15.580645
1328,28,79,50,9,28079050_9_47,2010,11,7.0,V,13.0,...,V,11.0,V,11.0,V,14.0,V,0.0,N,15.000000
1329,28,79,50,9,28079050_9_47,2010,12,10.0,V,11.0,...,V,19.0,V,16.0,V,15.0,V,12.0,V,15.633333

In [206]:
pm2010['total'].describe()

count    66.000000
mean     13.182540
std       3.092031
min       6.266667
25%      11.504032
50%      13.082796
75%      15.027778
max      22.857143
Name: total, dtype: float64

In [207]:
pm2013['total'].describe()

count    72.000000
mean     11.392446
std       2.850565
min       6.451613
25%       9.633929
50%      11.150000
75%      12.575000
max      23.225806
Name: total, dtype: float64

In [208]:
pm2015['total'].describe()

count    72.000000
mean     12.471818
std       4.249297
min       4.967742
25%       9.983871
50%      11.709677
75%      13.225806
max      26.516129
Name: total, dtype: float64

In [209]:
pm2017['total'].describe()

count    72.000000
mean     11.116881
std       1.970739
min       8.064516
25%       9.785484
50%      10.951075
75%      12.348214
max      16.548387
Name: total, dtype: float64

In [210]:
pm2019['total'].describe()

count    84.000000
mean     11.270451
std       3.314921
min       5.100000
25%       8.891667
50%      10.741935
75%      13.556452
max      20.870968
Name: total, dtype: float64

Exploring particles <10 micrograms
==

In [211]:
pm10_2010 = y2010[y2010['MAGNITUD'] == 10]
pm10_2010['total'] = [i for i in range(len(pm10_2010))]
pm10_2010['total'] = pm10_2010.apply(lambda x : pm_per_month(x), axis=1)
pm10_2010

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3210248712.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2010['total'] = [i for i in range(len(pm10_2010))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3210248712.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2010['total'] = pm10_2010.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2010,1,12.0,V,16.0,...,V,21.0,V,20.0,V,9.0,V,11.0,V,14.774194
121,28,79,8,10,28079008_10_47,2010,2,11.0,V,13.0,...,V,12.0,V,0.0,N,0.0,N,0.0,N,15.708333
122,28,79,8,10,28079008_10_47,2010,3,20.0,V,17.0,...,V,25.0,V,32.0,V,22.0,V,20.0,V,32.677419
123,28,79,8,10,28079008_10_47,2010,4,11.0,V,20.0,...,V,34.0,V,40.0,V,33.0,V,0.0,N,24.200000
124,28,79,8,10,28079008_10_47,2010,5,20.0,V,15.0,...,V,20.0,V,20.0,V,31.0,V,21.0,V,24.129032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1779,28,79,60,10,28079060_10_47,2010,8,0.0,N,0.0,...,V,22.0,V,18.0,V,15.0,V,36.0,V,33.000000
1780,28,79,60,10,28079060_10_47,2010,9,41.0,V,22.0,...,V,22.0,V,15.0,V,29.0,V,0.0,N,26.600000
1781,28,79,60,10,28079060_10_47,2010,10,25.0,V,25.0,...,V,47.0,V,43.0,V,7.0,V,10.0,V,26.000000
1782,28,79,60,10,28079060_10_47,2010,11,9.0,V,15.0,...,V,13.0,V,16.0,V,12.0,V,0.0,N,19.866667
1783,28,79,60,10,28079060_10_47,2010,12,10.0,V,13.0,...,V,33.0,V,26.0,V,22.0,V,14.0,V,21.387097

In [212]:
pm10_2011 = y2011[y2011['MAGNITUD'] == 10]
pm10_2011['total'] = [i for i in range(len(pm10_2011))]
pm10_2011['total'] = pm10_2011.apply(lambda x : pm_per_month(x), axis=1)
pm10_2011

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/227997542.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2011['total'] = [i for i in range(len(pm10_2011))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/227997542.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2011['total'] = pm10_2011.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2011,1,16.0,V,17.0,...,V,14.0,V,19.0,V,18.0,V,17.0,V,24.741935
121,28,79,8,10,28079008_10_47,2011,2,21.0,V,30.0,...,V,13.0,V,0.0,N,0.0,N,0.0,N,31.392857
122,28,79,8,10,28079008_10_47,2011,3,14.0,V,20.0,...,V,22.0,V,18.0,V,20.0,V,33.0,V,24.483871
123,28,79,8,10,28079008_10_47,2011,4,40.0,V,59.0,...,V,31.0,V,27.0,V,14.0,V,0.0,N,33.433333
124,28,79,8,10,28079008_10_47,2011,5,15.0,V,15.0,...,V,21.0,V,26.0,V,28.0,V,17.0,V,24.344828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819,28,79,60,10,28079060_10_47,2011,8,38.0,V,27.0,...,V,26.0,V,25.0,V,22.0,V,26.0,V,28.032258
1820,28,79,60,10,28079060_10_47,2011,9,15.0,V,11.0,...,V,24.0,V,30.0,V,23.0,V,0.0,N,26.666667
1821,28,79,60,10,28079060_10_47,2011,10,33.0,V,23.0,...,V,11.0,V,10.0,V,16.0,V,21.0,V,28.193548
1822,28,79,60,10,28079060_10_47,2011,11,22.0,V,23.0,...,V,28.0,V,37.0,V,36.0,V,0.0,N,23.533333
1823,28,79,60,10,28079060_10_47,2011,12,30.0,V,12.0,...,V,21.0,V,12.0,V,21.0,V,27.0,V,24.774194

In [213]:
pm10_2012 = y2012[y2012['MAGNITUD'] == 10]
pm10_2012['total'] = [i for i in range(len(pm10_2012))]
pm10_2012['total'] = pm10_2012.apply(lambda x : pm_per_month(x), axis=1)
pm10_2012

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/4144726719.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2012['total'] = [i for i in range(len(pm10_2012))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/4144726719.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2012['total'] = pm10_2012.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2012,1,37.0,V,13.0,...,V,8.0,V,9.0,V,27.0,V,31.0,V,27.580645
121,28,79,8,10,28079008_10_47,2012,2,32.0,V,14.0,...,V,34.0,V,34.0,V,0.0,N,0.0,N,20.413793
122,28,79,8,10,28079008_10_47,2012,3,37.0,V,36.0,...,V,39.0,V,30.0,V,32.0,V,37.0,V,30.322581
123,28,79,8,10,28079008_10_47,2012,4,38.0,V,24.0,...,V,10.0,V,9.0,V,14.0,V,0.0,N,18.200000
124,28,79,8,10,28079008_10_47,2012,5,13.0,V,16.0,...,V,26.0,V,31.0,V,46.0,V,40.0,V,27.129032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801,28,79,60,10,28079060_10_47,2012,8,22.0,V,21.0,...,V,22.0,V,25.0,V,26.0,V,13.0,V,39.419355
1802,28,79,60,10,28079060_10_47,2012,9,11.0,V,10.0,...,V,11.0,V,8.0,V,11.0,V,0.0,N,23.066667
1803,28,79,60,10,28079060_10_47,2012,10,19.0,V,22.0,...,V,9.0,V,16.0,V,14.0,V,16.0,V,23.935484
1804,28,79,60,10,28079060_10_47,2012,11,14.0,V,11.0,...,V,11.0,V,11.0,V,10.0,V,0.0,N,20.466667
1805,28,79,60,10,28079060_10_47,2012,12,9.0,V,15.0,...,V,17.0,V,15.0,V,10.0,V,8.0,V,17.838710

In [214]:
pm10_2013 = y2013[y2013['MAGNITUD'] == 10]
pm10_2013['total'] = [i for i in range(len(pm10_2013))]
pm10_2013['total'] = pm10_2013.apply(lambda x : pm_per_month(x), axis=1)
pm10_2013

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2018131712.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2013['total'] = [i for i in range(len(pm10_2013))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2018131712.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2013['total'] = pm10_2013.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2013,1,7.0,V,10.0,...,N,0.0,N,0.0,N,0.0,N,0.0,N,8.571429
121,28,79,8,10,28079008_10_47,2013,2,4.0,N,4.0,...,V,7.0,V,0.0,N,0.0,N,0.0,N,9.285714
122,28,79,8,10,28079008_10_47,2013,3,14.0,V,13.0,...,V,10.0,V,7.0,V,12.0,V,12.0,V,11.645161
123,28,79,8,10,28079008_10_47,2013,4,11.0,V,16.0,...,V,8.0,V,9.0,V,13.0,V,0.0,N,20.433333
124,28,79,8,10,28079008_10_47,2013,5,11.0,V,9.0,...,V,17.0,V,17.0,V,14.0,V,18.0,V,17.096774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,28,79,60,10,28079060_10_47,2013,8,51.0,V,46.0,...,V,33.0,V,19.0,V,21.0,V,17.0,V,34.322581
1784,28,79,60,10,28079060_10_47,2013,9,23.0,V,24.0,...,V,23.0,V,10.0,V,14.0,V,0.0,N,26.333333
1785,28,79,60,10,28079060_10_47,2013,10,10.0,V,19.0,...,V,19.0,V,11.0,V,12.0,V,20.0,V,21.193548
1786,28,79,60,10,28079060_10_47,2013,11,15.0,V,17.0,...,V,15.0,V,22.0,V,16.0,V,0.0,N,16.900000
1787,28,79,60,10,28079060_10_47,2013,12,6.0,V,16.0,...,V,6.0,V,11.0,V,12.0,V,11.0,V,18.483871

In [215]:
pm10_2014 = y2014[y2014['MAGNITUD'] == 10]
pm10_2014['total'] = [i for i in range(len(pm10_2014))]
pm10_2014['total'] = pm10_2014.apply(lambda x : pm_per_month(x), axis=1)
pm10_2014

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/963626272.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2014['total'] = [i for i in range(len(pm10_2014))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/963626272.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2014['total'] = pm10_2014.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2014,1,9.0,V,9.0,...,V,13.0,V,16.0,V,14.0,V,17.0,V,16.580645
121,28,79,8,10,28079008_10_47,2014,2,10.0,V,13.0,...,V,16.0,V,0.0,N,0.0,N,0.0,N,16.107143
122,28,79,8,10,28079008_10_47,2014,3,12.0,V,10.0,...,V,22.0,V,23.0,V,10.0,V,15.0,V,23.354839
123,28,79,8,10,28079008_10_47,2014,4,20.0,V,16.0,...,V,14.0,V,16.0,V,14.0,V,0.0,N,20.333333
124,28,79,8,10,28079008_10_47,2014,5,13.0,V,11.0,...,V,16.0,V,17.0,V,13.0,V,11.0,V,19.322581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1776,28,79,60,10,28079060_10_47,2014,8,34.0,V,18.0,...,V,26.0,V,25.0,V,30.0,V,20.0,V,26.580645
1777,28,79,60,10,28079060_10_47,2014,9,20.0,V,27.0,...,V,23.0,V,17.0,V,15.0,V,0.0,N,23.400000
1778,28,79,60,10,28079060_10_47,2014,10,25.0,V,23.0,...,V,43.0,V,39.0,V,35.0,V,30.0,V,29.806452
1779,28,79,60,10,28079060_10_47,2014,11,29.0,V,26.0,...,V,11.0,V,9.0,V,15.0,V,0.0,N,25.433333
1780,28,79,60,10,28079060_10_47,2014,12,13.0,V,10.0,...,V,15.0,V,13.0,V,21.0,V,33.0,V,23.096774

In [216]:
pm10_2015 = y2015[y2015['MAGNITUD'] == 10]
pm10_2015['total'] = [i for i in range(len(pm10_2015))]
pm10_2015['total'] = pm10_2015.apply(lambda x : pm_per_month(x), axis=1)
pm10_2015

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3383298957.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2015['total'] = [i for i in range(len(pm10_2015))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3383298957.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2015['total'] = pm10_2015.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2015,1,42.0,V,36.0,...,V,24.0,V,21.0,V,10.0,V,7.0,V,21.129032
121,28,79,8,10,28079008_10_47,2015,2,8.0,V,10.0,...,V,20.0,V,0.0,N,0.0,N,0.0,N,16.607143
122,28,79,8,10,28079008_10_47,2015,3,16.0,V,24.0,...,V,23.0,V,14.0,V,20.0,V,28.0,V,22.580645
123,28,79,8,10,28079008_10_47,2015,4,16.0,V,16.0,...,V,9.0,V,14.0,V,22.0,V,0.0,N,20.300000
124,28,79,8,10,28079008_10_47,2015,5,17.0,V,16.0,...,V,31.0,V,32.0,V,24.0,V,23.0,V,23.709677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,28,79,60,10,28079060_10_47,2015,8,6.0,V,19.0,...,V,22.0,V,32.0,V,34.0,V,31.0,V,28.483871
1784,28,79,60,10,28079060_10_47,2015,9,16.0,V,18.0,...,V,12.0,V,11.0,V,11.0,V,0.0,N,16.266667
1785,28,79,60,10,28079060_10_47,2015,10,11.0,V,13.0,...,V,8.0,V,14.0,V,18.0,V,15.0,V,19.258065
1786,28,79,60,10,28079060_10_47,2015,11,10.0,V,7.0,...,V,12.0,V,15.0,V,26.0,V,0.0,N,22.900000
1787,28,79,60,10,28079060_10_47,2015,12,24.0,V,34.0,...,V,22.0,V,12.0,V,11.0,V,10.0,V,27.935484

In [217]:
pm10_2016 = y2016[y2016['MAGNITUD'] == 10]
pm10_2016['total'] = [i for i in range(len(pm10_2016))]
pm10_2016['total'] = pm10_2016.apply(lambda x : pm_per_month(x), axis=1)
pm10_2016

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3770725947.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2016['total'] = [i for i in range(len(pm10_2016))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3770725947.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2016['total'] = pm10_2016.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2016,1,20.0,V,13.0,...,V,30.0,V,15.0,V,17.0,V,18.0,V,20.064516
121,28,79,8,10,28079008_10_47,2016,2,34.0,V,42.0,...,V,7.0,V,14.0,V,0.0,N,0.0,N,25.689655
122,28,79,8,10,28079008_10_47,2016,3,25.0,V,24.0,...,V,14.0,V,17.0,V,26.0,V,11.0,V,17.064516
123,28,79,8,10,28079008_10_47,2016,4,10.0,V,16.0,...,V,9.0,V,13.0,V,10.0,V,0.0,N,12.333333
124,28,79,8,10,28079008_10_47,2016,5,7.0,V,9.0,...,V,13.0,V,10.0,V,11.0,V,10.0,V,14.838710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,28,79,60,10,28079060_10_47,2016,8,16.0,V,24.0,...,V,61.0,V,32.0,V,22.0,V,30.0,V,30.193548
1784,28,79,60,10,28079060_10_47,2016,9,23.0,V,19.0,...,V,11.0,V,24.0,V,21.0,V,0.0,N,25.166667
1785,28,79,60,10,28079060_10_47,2016,10,24.0,V,18.0,...,V,41.0,V,21.0,V,11.0,V,20.0,V,27.322581
1786,28,79,60,10,28079060_10_47,2016,11,23.0,V,30.0,...,V,16.0,V,16.0,V,9.0,V,0.0,N,20.500000
1787,28,79,60,10,28079060_10_47,2016,12,9.0,V,14.0,...,V,15.0,V,20.0,V,19.0,V,13.0,V,17.387097

In [218]:
pm10_2017 = y2017[y2017['MAGNITUD'] == 10]
pm10_2017['total'] = [i for i in range(len(pm10_2017))]
pm10_2017['total'] = pm10_2017.apply(lambda x : pm_per_month(x), axis=1)
pm10_2017

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/4037048677.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2017['total'] = [i for i in range(len(pm10_2017))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/4037048677.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2017['total'] = pm10_2017.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2017,1,25.0,V,25.0,...,V,9.0,V,12.0,V,12.0,V,19.0,V,20.032258
121,28,79,8,10,28079008_10_47,2017,2,26.0,V,11.0,...,V,12.0,V,0.0,N,0.0,N,0.0,N,25.035714
122,28,79,8,10,28079008_10_47,2017,3,15.0,V,24.0,...,V,18.0,V,23.0,V,27.0,V,22.0,V,19.193548
123,28,79,8,10,28079008_10_47,2017,4,10.0,V,8.0,...,V,13.0,V,10.0,V,11.0,V,0.0,N,19.133333
124,28,79,8,10,28079008_10_47,2017,5,9.0,V,13.0,...,V,26.0,V,24.0,V,18.0,V,24.0,V,19.806452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783,28,79,60,10,28079060_10_47,2017,8,27.0,V,27.0,...,V,22.0,V,12.0,V,10.0,V,9.0,V,31.548387
1784,28,79,60,10,28079060_10_47,2017,9,5.0,V,8.0,...,V,30.0,V,33.0,V,26.0,V,0.0,N,20.000000
1785,28,79,60,10,28079060_10_47,2017,10,14.0,V,12.0,...,V,10.0,V,6.0,V,9.0,V,20.0,V,23.903226
1786,28,79,60,10,28079060_10_47,2017,11,16.0,V,19.0,...,V,35.0,V,11.0,V,10.0,V,0.0,N,20.366667
1787,28,79,60,10,28079060_10_47,2017,12,8.0,V,7.0,...,V,9.0,V,11.0,V,8.0,V,10.0,V,18.258065

In [219]:
pm10_2018 = y2018[y2018['MAGNITUD'] == 10]
pm10_2018['total'] = [i for i in range(len(pm10_2018))]
pm10_2018['total'] = pm10_2018.apply(lambda x : pm_per_month(x), axis=1)
pm10_2018

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2221148439.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2018['total'] = [i for i in range(len(pm10_2018))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/2221148439.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2018['total'] = pm10_2018.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2018,1,9.0,V,10.0,...,V,6.0,V,15.0,V,18.0,V,19.0,V,13.451613
121,28,79,8,10,28079008_10_47,2018,2,21.0,V,7.0,...,V,9.0,V,0.0,N,0.0,N,0.0,N,12.107143
122,28,79,8,10,28079008_10_47,2018,3,4.0,V,11.0,...,V,12.0,V,6.0,V,4.0,V,4.0,V,7.032258
123,28,79,8,10,28079008_10_47,2018,4,7.0,V,10.0,...,V,13.0,V,5.0,V,4.0,V,0.0,N,12.033333
124,28,79,8,10,28079008_10_47,2018,5,4.0,V,8.0,...,V,9.0,V,12.0,V,10.0,V,11.0,V,10.419355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1777,28,79,60,10,28079060_10_47,2018,8,33.0,V,39.0,...,V,34.0,V,25.0,V,24.0,V,20.0,V,33.387097
1778,28,79,60,10,28079060_10_47,2018,9,19.0,V,26.0,...,V,20.0,V,15.0,V,16.0,V,0.0,N,23.800000
1779,28,79,60,10,28079060_10_47,2018,10,11.0,V,9.0,...,V,5.0,V,7.0,V,11.0,V,8.0,V,18.064516
1780,28,79,60,10,28079060_10_47,2018,11,13.0,V,8.0,...,V,29.0,V,24.0,V,14.0,V,0.0,N,16.900000
1781,28,79,60,10,28079060_10_47,2018,12,14.0,V,19.0,...,V,18.0,V,7.0,V,11.0,V,22.0,V,20.225806

In [220]:
pm10_2019 = y2019[y2019['MAGNITUD'] == 10]
pm10_2019['total'] = [i for i in range(len(pm10_2019))]
pm10_2019['total'] = pm10_2019.apply(lambda x : pm_per_month(x), axis=1)
pm10_2019

/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3432944937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2019['total'] = [i for i in range(len(pm10_2019))]
/var/folders/n3/xb6jll3d49q147jw5_13y6zm0000gn/T/ipykernel_2460/3432944937.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pm10_2019['total'] = pm10_2019.apply(lambda x : pm_per_month(x), axis=1)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2019,1,32.0,V,37.0,...,V,13.0,V,16.0,V,12.0,V,11.0,V,25.516129
121,28,79,8,10,28079008_10_47,2019,2,8.0,V,8.0,...,V,38.0,V,0.0,N,0.0,N,0.0,N,30.607143
122,28,79,8,10,28079008_10_47,2019,3,29.0,V,31.0,...,V,27.0,V,23.0,V,28.0,V,20.0,V,25.419355
123,28,79,8,10,28079008_10_47,2019,4,15.0,V,19.0,...,V,13.0,V,16.0,V,15.0,V,0.0,N,14.566667
124,28,79,8,10,28079008_10_47,2019,5,13.0,V,11.0,...,V,10.0,V,12.0,V,11.0,V,21.0,V,15.064516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1807,28,79,60,10,28079060_10_47,2019,8,17.0,V,18.0,...,V,14.0,V,16.0,V,13.0,V,10.0,V,19.903226
1808,28,79,60,10,28079060_10_47,2019,9,15.0,V,10.0,...,V,10.0,V,11.0,V,11.0,V,0.0,N,15.666667
1809,28,79,60,10,28079060_10_47,2019,10,16.0,V,7.0,...,V,14.0,V,24.0,V,15.0,V,6.0,V,15.580645
1810,28,79,60,10,28079060_10_47,2019,11,5.0,V,4.0,...,V,4.0,V,4.0,V,2.0,V,0.0,N,9.833333
1811,28,79,60,10,28079060_10_47,2019,12,2.0,V,2.0,...,V,14.0,V,15.0,V,19.0,V,25.0,V,15.419355

In [221]:
pm10_2011['total'].describe()

count    144.000000
mean      25.798944
std        4.739754
min       16.193548
25%       22.758333
50%       24.882184
75%       28.354839
max       41.533333
Name: total, dtype: float64

In [224]:
pm10_2013['total'].describe()

count    144.000000
mean      21.075492
std        8.782510
min        8.571429
25%       16.112903
50%       19.077957
75%       24.708333
max       92.928571
Name: total, dtype: float64

In [225]:
pm10_2015['total'].describe()

count    144.000000
mean      27.601130
std       52.189683
min        6.500000
25%       19.161828
50%       22.100000
75%       27.137097
max      644.709677
Name: total, dtype: float64

In [226]:
pm10_2014['total'].describe()

count    144.000000
mean      21.649641
std        4.570365
min        9.785714
25%       19.290323
50%       21.655376
75%       24.386290
max       35.290323
Name: total, dtype: float64

In [227]:
pm10_2017['total'].describe()

count    144.000000
mean      22.338022
std        5.156026
min       12.258065
25%       18.218548
50%       21.684946
75%       25.719758
max       34.642857
Name: total, dtype: float64

In [228]:
pm10_2018['total'].describe()

count    144.000000
mean      21.295465
std       14.573757
min        5.800000
25%       14.124194
50%       20.130760
75%       24.683333
max      173.933333
Name: total, dtype: float64

In [229]:
pm10_2019['total'].describe()

count    156.000000
mean      20.119061
std        6.123129
min        7.833333
25%       15.645161
50%       19.322581
75%       24.303571
max       37.000000
Name: total, dtype: float64

---

Saving transformed data
==

In [230]:
pm2010.to_csv('../data/transformed-data/pm_2010.csv')
pm2011.to_csv('../data/transformed-data/pm_2011.csv')
pm2012.to_csv('../data/transformed-data/pm_2012.csv')
pm2013.to_csv('../data/transformed-data/pm_2013.csv')
pm2014.to_csv('../data/transformed-data/pm_2014.csv')
pm2015.to_csv('../data/transformed-data/pm_2015.csv')
pm2016.to_csv('../data/transformed-data/pm_2016.csv')
pm2017.to_csv('../data/transformed-data/pm_2017.csv')
pm2018.to_csv('../data/transformed-data/pm_2018.csv')
pm2019.to_csv('../data/transformed-data/pm_2019.csv')

In [231]:
pm10_2010.to_csv('../data/transformed-data/pm10_2010.csv')
pm10_2011.to_csv('../data/transformed-data/pm10_2011.csv')
pm10_2012.to_csv('../data/transformed-data/pm10_2012.csv')
pm10_2013.to_csv('../data/transformed-data/pm10_2013.csv')
pm10_2014.to_csv('../data/transformed-data/pm10_2014.csv')
pm10_2015.to_csv('../data/transformed-data/pm10_2015.csv')
pm10_2016.to_csv('../data/transformed-data/pm10_2016.csv')
pm10_2017.to_csv('../data/transformed-data/pm10_2017.csv')
pm10_2018.to_csv('../data/transformed-data/pm10_2018.csv')
pm10_2019.to_csv('../data/transformed-data/pm10_2019.csv')

In [242]:
pm10_2019

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,V27,D28,V28,D29,V29,D30,V30,D31,V31,total
120,28,79,8,10,28079008_10_47,2019,1,32.0,V,37.0,...,V,13.0,V,16.0,V,12.0,V,11.0,V,25.516129
121,28,79,8,10,28079008_10_47,2019,2,8.0,V,8.0,...,V,38.0,V,0.0,N,0.0,N,0.0,N,30.607143
122,28,79,8,10,28079008_10_47,2019,3,29.0,V,31.0,...,V,27.0,V,23.0,V,28.0,V,20.0,V,25.419355
123,28,79,8,10,28079008_10_47,2019,4,15.0,V,19.0,...,V,13.0,V,16.0,V,15.0,V,0.0,N,14.566667
124,28,79,8,10,28079008_10_47,2019,5,13.0,V,11.0,...,V,10.0,V,12.0,V,11.0,V,21.0,V,15.064516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1807,28,79,60,10,28079060_10_47,2019,8,17.0,V,18.0,...,V,14.0,V,16.0,V,13.0,V,10.0,V,19.903226
1808,28,79,60,10,28079060_10_47,2019,9,15.0,V,10.0,...,V,10.0,V,11.0,V,11.0,V,0.0,N,15.666667
1809,28,79,60,10,28079060_10_47,2019,10,16.0,V,7.0,...,V,14.0,V,24.0,V,15.0,V,6.0,V,15.580645
1810,28,79,60,10,28079060_10_47,2019,11,5.0,V,4.0,...,V,4.0,V,4.0,V,2.0,V,0.0,N,9.833333
1811,28,79,60,10,28079060_10_47,2019,12,2.0,V,2.0,...,V,14.0,V,15.0,V,19.0,V,25.0,V,15.419355

In [234]:
pm2019['total'].describe()

count    84.000000
mean     11.270451
std       3.314921
min       5.100000
25%       8.891667
50%      10.741935
75%      13.556452
max      20.870968
Name: total, dtype: float64